language: java

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "mvn clean deploy --settings target/travis/dsettings.xml"

branches:
  except:
    - travis
